#!/usr/bin/env bash
set -euo pipefail

CFG="${1:-}"
[[ -n "${CFG}" && -f "${CFG}" ]] || { echo "Usage: $0 <config.env>" >&2; exit 1; }
# shellcheck disable=SC1090
source "${CFG}"

# Defaults (prevent unbound-variable failures)
: "${DX_PROJECT_ID:?Must set DX_PROJECT_ID in config}"
: "${SRC_PROJ:?Must set SRC_PROJ in config}"
: "${CHR:=22}"
: "${DEST_INPUTS:=/inputs/rv_portability/saige_chr22_plumbing}"
: "${DEST_SAIGE:=/saige/chr22_test}"
: "${DEST_PERSIST:=/persist/rv_portability/saige_chr22_plumbing}"
: "${DX_LOG_DIR:=/persist/logs/rv_portability/saige_chr22_plumbing}"
: "${TMP_BASE:=/opt/notebooks/work/tmp/rvp_saige_chr22}"

# Test knobs (kept for future; not used for local plink subsampling)
: "${TEST_MODE:=1}"
: "${TEST_N_INDIV:=50000}"
: "${TEST_N_VARIANTS:=5000}"

die() { echo "ERROR: $*" >&2; exit 1; }

dx_find_one_or_die() {
  local p="$1"
  local n="$2"
  local id
  id="$(dx find data --path "$p" --name "$n" --brief | head -n 1 || true)"
  [[ -n "${id:-}" ]] || die "Could not find '$n' under path: $p"
  echo "$id"
}

echo "=============================="
echo "[INFO] Stage 01: prepare inputs"
echo "[INFO] CFG=${CFG}"
echo "[INFO] Using DNAnexus project: ${DX_PROJECT_ID}"
echo "=============================="

dx select "${DX_PROJECT_ID}" >/dev/null
echo "[INFO] dx pwd: $(dx pwd)"

# Define UKB OQFE paths
EXOME_BASE="${SRC_PROJ}:/Bulk/Exome sequences"
BGEN_FINAL="${EXOME_BASE}/Population level exome OQFE variants, BGEN format - final release"
PLINK_FINAL="${EXOME_BASE}/Population level exome OQFE variants, PLINK format - final release"

BGEN_NAME="ukb23159_c${CHR}_b0_v1.bgen"
BGI_NAME="ukb23159_c${CHR}_b0_v1.bgen.bgi"
SAMPLE_NAME="ukb23159_c${CHR}_b0_v1.sample"

PLINK_PREFIX="ukb23158_c${CHR}_b0_v1"
BED_NAME="${PLINK_PREFIX}.bed"
BIM_NAME="${PLINK_PREFIX}.bim"
FAM_NAME="${PLINK_PREFIX}.fam"

echo "=============================="
echo "[INFO] Resolving BGEN/BGI/SAMPLE IDs..."
BGEN_ID="$(dx_find_one_or_die "$BGEN_FINAL" "$BGEN_NAME")"
BGI_ID="$(dx_find_one_or_die "$BGEN_FINAL" "$BGI_NAME")"
SAMPLE_ID="$(dx_find_one_or_die "$BGEN_FINAL" "$SAMPLE_NAME")"

echo "[INFO] Resolving PLINK bed/bim/fam IDs..."
BED_ID="$(dx_find_one_or_die "$PLINK_FINAL" "$BED_NAME")"
BIM_ID="$(dx_find_one_or_die "$PLINK_FINAL" "$BIM_NAME")"
FAM_ID="$(dx_find_one_or_die "$PLINK_FINAL" "$FAM_NAME")"

echo "[INFO] BGEN_ID=${BGEN_ID}"
echo "[INFO] BGI_ID=${BGI_ID}"
echo "[INFO] SAMPLE_ID=${SAMPLE_ID}"
echo "[INFO] BED_ID=${BED_ID}"
echo "[INFO] BIM_ID=${BIM_ID}"
echo "[INFO] FAM_ID=${FAM_ID}"
echo "=============================="

# Create destination folders in current project
echo "[INFO] Creating destination folders in current project..."
dx mkdir -p "${DEST_INPUTS}" >/dev/null || true
dx mkdir -p "${DEST_SAIGE}"  >/dev/null || true
dx mkdir -p "${DEST_PERSIST}" >/dev/null || true
dx mkdir -p "${DX_LOG_DIR}" >/dev/null || true

# Build dummy phenotype (IID, pheno, sex) from .fam
mkdir -p "${TMP_BASE}"
LOCAL_FAM="${TMP_BASE}/${FAM_NAME}"
PHENO_LOCAL="${TMP_BASE}/pheno_dummy_for_saige.tsv"

echo "[INFO] Downloading FAM to build dummy phenotype file..."
dx download "${FAM_ID}" -o "${LOCAL_FAM}" --overwrite

echo "[INFO] Creating dummy phenotype file: ${PHENO_LOCAL}"
awk 'BEGIN{OFS="\t"; print "IID","pheno","sex"} {print $2,0,$5}' "${LOCAL_FAM}" > "${PHENO_LOCAL}"

echo "[INFO] Preview phenotype file:"
head -n 5 "${PHENO_LOCAL}" || true
echo "=============================="

echo "[INFO] Uploading phenotype file to ${DEST_INPUTS} ..."
# NOTE: dx upload does NOT have --overwrite; it will create a new file version.
PHENO_ID="$(dx upload "${PHENO_LOCAL}" --path "${DEST_INPUTS}" --brief --parents)"
echo "[INFO] PHENO_ID=${PHENO_ID}"
echo "=============================="

# Write manifest_ids.env locally + persist to DNAnexus
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST_LOCAL="${ROOT}/configs/manifest_ids.env"

cat > "${MANIFEST_LOCAL}" <<MAN
# Auto-generated by 01_prepare_inputs.sh on $(date -u)
BGEN_ID="${BGEN_ID}"
BGI_ID="${BGI_ID}"
SAMPLE_ID="${SAMPLE_ID}"
PLINK_BED_ID="${BED_ID}"
PLINK_BIM_ID="${BIM_ID}"
PLINK_FAM_ID="${FAM_ID}"
PHENO_ID="${PHENO_ID}"
MAN

echo "[OK] Wrote local manifest: ${MANIFEST_LOCAL}"

# Replace persisted manifest (stable filename) by removing old then uploading
dx rm -f "${DX_PROJECT_ID}:${DEST_PERSIST}/manifest_ids.env" >/dev/null 2>&1 || true
dx upload "${MANIFEST_LOCAL}" --path "${DEST_PERSIST}" --parents >/dev/null
echo "[OK] Persisted manifest to: ${DEST_PERSIST}/manifest_ids.env"

# Write / refresh state env locally (job IDs get appended later)
STATE_LOCAL="${ROOT}/configs/chr22_plumbing.state.env"
cat > "${STATE_LOCAL}" <<STATE
# Auto-generated by 01_prepare_inputs.sh on $(date -u)
MANIFEST_LOCAL="${MANIFEST_LOCAL}"
DEST_PERSIST="${DEST_PERSIST}"
DEST_SAIGE="${DEST_SAIGE}"
STATE

dx rm -f "${DX_PROJECT_ID}:${DEST_PERSIST}/chr22_plumbing.state.env" >/dev/null 2>&1 || true
dx upload "${STATE_LOCAL}" --path "${DEST_PERSIST}" --parents >/dev/null
echo "[OK] Persisted state file to: ${DEST_PERSIST}/chr22_plumbing.state.env"

echo "[OK] Stage 01 complete."
