#!/usr/bin/env bash
set -euo pipefail

CFG="${1:-}"
[[ -n "${CFG}" && -f "${CFG}" ]] || { echo "Usage: $0 <config.env>" >&2; exit 1; }
# shellcheck disable=SC1090
source "${CFG}"

: "${DX_PROJECT_ID:?Must set DX_PROJECT_ID in config}"
: "${DEST_PERSIST:=/persist/rv_portability/saige_chr22_plumbing}"
: "${DEST_SAIGE:=/saige/chr22_test}"
: "${APP_SPARSE_GRM:=saige_gwas_sparse_grm}"
: "${CHR:=22}"

: "${TEST_MODE:=1}"
: "${TEST_INSTANCE_TYPE:=mem1_hdd1_v2_x16}"
: "${FULL_INSTANCE_TYPE:=mem1_hdd1_v2_x72}"
: "${NUM_RANDOM_MARKER:=500}"
: "${RELATEDNESS_CUTOFF:=0.125}"

die() { echo "ERROR: $*" >&2; exit 1; }

echo "=============================="
echo "[INFO] Stage 02: submit sparse GRM"
echo "[INFO] CFG=${CFG}"
echo "[INFO] DX_PROJECT_ID=${DX_PROJECT_ID}"
echo "=============================="

dx select "${DX_PROJECT_ID}" >/dev/null

# Load manifest from DNAnexus persist (preferred, survives Jupyter restarts)
MANIFEST_DX="${DX_PROJECT_ID}:${DEST_PERSIST}/manifest_ids.env"
dx download "${MANIFEST_DX}" -o /tmp/manifest_ids.env --overwrite >/dev/null
# shellcheck disable=SC1091
source /tmp/manifest_ids.env

: "${PLINK_BED_ID:?Missing PLINK_BED_ID in manifest}"
: "${PLINK_BIM_ID:?Missing PLINK_BIM_ID in manifest}"
: "${PLINK_FAM_ID:?Missing PLINK_FAM_ID in manifest}"

INSTANCE="${FULL_INSTANCE_TYPE}"
if [[ "${TEST_MODE}" -eq 1 ]]; then INSTANCE="${TEST_INSTANCE_TYPE}"; fi

OUT_PREFIX="wes_oqfe_chr${CHR}_sparseGRM_testmode${TEST_MODE}"

echo "[INFO] instance-type: ${INSTANCE}"
echo "[INFO] output_prefix: ${OUT_PREFIX}"
echo "[INFO] destination: ${DEST_SAIGE}"

JOB_ID="$(dx run "${APP_SPARSE_GRM}" \
  --yes --brief \
  --instance-type "${INSTANCE}" \
  -iplink_bed="${PLINK_BED_ID}" \
  -iplink_bim="${PLINK_BIM_ID}" \
  -iplink_fam="${PLINK_FAM_ID}" \
  -inum_random_marker="${NUM_RANDOM_MARKER}" \
  -irelatedness_cutoff="${RELATEDNESS_CUTOFF}" \
  -ioutput_prefix="${OUT_PREFIX}" \
  --destination "${DEST_SAIGE}")"

echo "[OK] Submitted sparse GRM job: ${JOB_ID}"
echo "[INFO] Watch with: dx watch ${JOB_ID}"

# Update state env locally then persist to DNAnexus
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_LOCAL="${ROOT}/configs/chr22_plumbing.state.env"

# Ensure local state exists (stage01 writes it; but create if missing)
if [[ ! -f "${STATE_LOCAL}" ]]; then
  cat > "${STATE_LOCAL}" <<STATE
# Auto-generated by 02_submit_step0_sparse_grm_dx.sh on $(date -u)
DEST_PERSIST="${DEST_PERSIST}"
DEST_SAIGE="${DEST_SAIGE}"
STATE
fi

# Append job id (idempotent-ish: record every submission with timestamp)
{
  echo ""
  echo "# Added by 02_submit_step0_sparse_grm_dx.sh on $(date -u)"
  echo "SPARSE_JOB_ID=\"${JOB_ID}\""
  echo "SPARSE_OUT_PREFIX=\"${OUT_PREFIX}\""
} >> "${STATE_LOCAL}"

# Replace persisted state file
dx rm -f "${DX_PROJECT_ID}:${DEST_PERSIST}/chr22_plumbing.state.env" >/dev/null 2>&1 || true
dx upload "${STATE_LOCAL}" --path "${DEST_PERSIST}" --parents >/dev/null

echo "[OK] Updated state persisted: ${DEST_PERSIST}/chr22_plumbing.state.env"
