#!/usr/bin/env bash
set -euo pipefail

CFG="${1:-}"
[[ -n "${CFG}" && -f "${CFG}" ]] || { echo "Usage: $0 <config.env>" >&2; exit 1; }
# shellcheck disable=SC1090
source "${CFG}"

: "${DX_PROJECT_ID:?Must set DX_PROJECT_ID in config}"
: "${DEST_PERSIST:=/persist/rv_portability/saige_chr22_plumbing}"
: "${DEST_SAIGE:=/saige/chr22_test}"
: "${APP_NULL_MODEL:=saige_gwas_grm}"
: "${CHR:=22}"

: "${TEST_MODE:=1}"
: "${TEST_INSTANCE_TYPE:=mem1_hdd1_v2_x16}"
: "${FULL_INSTANCE_TYPE:=mem1_hdd1_v2_x72}"

: "${PHENO_COL:=pheno}"
: "${SAMPLE_ID_COL:=IID}"
: "${COVARIATES:=sex}"
: "${TRAIT_TYPE:=quantitative}"
: "${INVERSE_NORMALIZE:=false}"

die() { echo "ERROR: $*" >&2; exit 1; }

resolve_dx_file_id_by_name_in_folder() {
  local folder="$1"
  local name="$2"
  dx find data --path "${folder}" --name "${name}" --brief | head -n 1
}

download_named_from_persist() {
  # usage: download_named_from_persist "manifest_ids.env" "/tmp/manifest_ids.env"
  local name="$1"
  local out="$2"
  local dx_path="${DX_PROJECT_ID}:${DEST_PERSIST}/${name}"

  if dx download "${dx_path}" -o "${out}" -f >/dev/null 2>&1; then
    echo "${out}"
    return 0
  fi

  local file_id
  file_id="$(resolve_dx_file_id_by_name_in_folder "${DEST_PERSIST}" "${name}" || true)"
  [[ -n "${file_id:-}" ]] || die "Could not find ${name} in ${DEST_PERSIST}. Run Stage 01 and verify: dx ls ${DEST_PERSIST}"

  dx download "${file_id}" -o "${out}" -f >/dev/null
  echo "${out}"
}

echo "=============================="
echo "[INFO] Stage 03: submit null model (Step1)"
echo "[INFO] CFG=${CFG}"
echo "[INFO] DX_PROJECT_ID=${DX_PROJECT_ID}"
echo "[INFO] DEST_PERSIST=${DEST_PERSIST}"
echo "=============================="

dx select "${DX_PROJECT_ID}" >/dev/null

MANIFEST_LOCAL="$(download_named_from_persist "manifest_ids.env" "/tmp/manifest_ids.env")"
# shellcheck disable=SC1090
source "${MANIFEST_LOCAL}"

: "${PLINK_BED_ID:?Missing PLINK_BED_ID in manifest}"
: "${PLINK_BIM_ID:?Missing PLINK_BIM_ID in manifest}"
: "${PLINK_FAM_ID:?Missing PLINK_FAM_ID in manifest}"
: "${PHENO_ID:?Missing PHENO_ID in manifest}"

# (Optional) state file just for provenance; not required to submit Step1
STATE_LOCAL_TMP="/tmp/chr22_plumbing.state.env"
download_named_from_persist "chr22_plumbing.state.env" "${STATE_LOCAL_TMP}" >/dev/null 2>&1 || true
# shellcheck disable=SC1091
source "${STATE_LOCAL_TMP}" 2>/dev/null || true

INSTANCE="${FULL_INSTANCE_TYPE}"
if [[ "${TEST_MODE}" -eq 1 ]]; then INSTANCE="${TEST_INSTANCE_TYPE}"; fi

OUT_PREFIX="wes_oqfe_chr${CHR}_null_testmode${TEST_MODE}"

echo "[INFO] instance-type: ${INSTANCE}"
echo "[INFO] output_prefix: ${OUT_PREFIX}"
echo "[INFO] destination: ${DEST_SAIGE}"
echo "[INFO] covariates: ${COVARIATES}"
echo "[INFO] trait_type: ${TRAIT_TYPE}"

JOB_ID="$(dx run "${APP_NULL_MODEL}" \
  --yes --brief \
  --instance-type "${INSTANCE}" \
  -iplink_bed="${PLINK_BED_ID}" \
  -iplink_bim="${PLINK_BIM_ID}" \
  -iplink_fam="${PLINK_FAM_ID}" \
  -iphenotype_file="${PHENO_ID}" \
  -ipheno_col="${PHENO_COL}" \
  -icovariates="${COVARIATES}" \
  -isample_id_col="${SAMPLE_ID_COL}" \
  -itrait_type="${TRAIT_TYPE}" \
  -iinverse_normalize="${INVERSE_NORMALIZE}" \
  -ioutput_file_prefix="${OUT_PREFIX}" \
  --destination "${DEST_SAIGE}")"

echo "[OK] Submitted null model job: ${JOB_ID}"
echo "[INFO] Watch with: dx watch ${JOB_ID}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_LOCAL="${ROOT}/configs/chr22_plumbing.state.env"

if [[ ! -f "${STATE_LOCAL}" ]]; then
  cat > "${STATE_LOCAL}" <<STATE
# Auto-generated by 03_submit_step1_null_model_dx.sh on $(date -u)
DEST_PERSIST="${DEST_PERSIST}"
DEST_SAIGE="${DEST_SAIGE}"
STATE
fi

{
  echo ""
  echo "# Added by 03_submit_step1_null_model_dx.sh on $(date -u)"
  echo "NULL_JOB_ID=\"${JOB_ID}\""
  echo "NULL_OUT_PREFIX=\"${OUT_PREFIX}\""
} >> "${STATE_LOCAL}"

dx rm -f "${DX_PROJECT_ID}:${DEST_PERSIST}/chr22_plumbing.state.env" >/dev/null 2>&1 || true
dx upload "${STATE_LOCAL}" --path "${DEST_PERSIST}" --parents >/dev/null

echo "[OK] Updated state persisted: ${DEST_PERSIST}/chr22_plumbing.state.env"
