#!/usr/bin/env bash
set -euo pipefail

CFG="${1:-}"
[[ -n "${CFG}" && -f "${CFG}" ]] || { echo "Usage: $0 <config.env>" >&2; exit 1; }
# shellcheck disable=SC1090
source "${CFG}"

: "${DX_PROJECT_ID:?Must set DX_PROJECT_ID in config}"
: "${DEST_PERSIST:=/persist/rv_portability/saige_chr22_plumbing}"
: "${DEST_SAIGE:=/saige/chr22_test}"
: "${APP_GBAT:=saige_gwas_gbat}"
: "${CHR:=22}"

: "${TEST_MODE:=1}"
: "${TEST_INSTANCE_TYPE:=mem1_hdd1_v2_x16}"
: "${FULL_INSTANCE_TYPE:=mem1_hdd1_v2_x72}"

: "${TEST_RANGE_START:=1}"
: "${TEST_RANGE_END:=5000000}"

die() { echo "ERROR: $*" >&2; exit 1; }

resolve_dx_file_id_by_name_in_folder() {
  local folder="$1"
  local name="$2"
  dx find data --path "${folder}" --name "${name}" --brief | head -n 1
}

download_named_from_persist() {
  local name="$1"
  local out="$2"
  local dx_path="${DX_PROJECT_ID}:${DEST_PERSIST}/${name}"

  if dx download "${dx_path}" -o "${out}" -f >/dev/null 2>&1; then
    echo "${out}"
    return 0
  fi

  local file_id
  file_id="$(resolve_dx_file_id_by_name_in_folder "${DEST_PERSIST}" "${name}" || true)"
  [[ -n "${file_id:-}" ]] || die "Could not find ${name} in ${DEST_PERSIST}. Verify: dx ls ${DEST_PERSIST}"

  dx download "${file_id}" -o "${out}" -f >/dev/null
  echo "${out}"
}

echo "=============================="
echo "[INFO] Stage 04: submit Step2 GBAT"
echo "[INFO] CFG=${CFG}"
echo "[INFO] DX_PROJECT_ID=${DX_PROJECT_ID}"
echo "=============================="

dx select "${DX_PROJECT_ID}" >/dev/null

MANIFEST_LOCAL="$(download_named_from_persist "manifest_ids.env" "/tmp/manifest_ids.env")"
# shellcheck disable=SC1090
source "${MANIFEST_LOCAL}"

: "${BGEN_ID:?Missing BGEN_ID in manifest}"
: "${BGI_ID:?Missing BGI_ID in manifest}"
: "${SAMPLE_ID:?Missing SAMPLE_ID in manifest}"

# You must set these in chr22_plumbing.env once Step1 completes:
: "${MODEL_RDA_ID:=}"
: "${VARIANCE_RATIO_ID:=}"
: "${SPARSE_SIGMA_MTX_ID:=}"
: "${GROUP_TXT_ID:=}"

if [[ -z "${MODEL_RDA_ID}" || -z "${VARIANCE_RATIO_ID}" || -z "${SPARSE_SIGMA_MTX_ID}" || -z "${GROUP_TXT_ID}" ]]; then
  cat >&2 <<MSG
ERROR: Missing one or more required Step2 inputs.
Please set these in configs/chr22_plumbing.env (copy/paste file IDs):
  MODEL_RDA_ID="file-..."
  VARIANCE_RATIO_ID="file-..."
  SPARSE_SIGMA_MTX_ID="file-..."
  GROUP_TXT_ID="file-..."

To find after Step1 finishes:
  dx ls ${DEST_SAIGE}
  dx find data --path "${DX_PROJECT_ID}:${DEST_SAIGE}" --name "*.rda" --brief | head
  dx find data --path "${DX_PROJECT_ID}:${DEST_SAIGE}" --name "*varianceRatio*" --brief | head
  dx find data --path "${DX_PROJECT_ID}:${DEST_SAIGE}" --name "*sigma*" --brief | head
MSG
  exit 1
fi

INSTANCE="${FULL_INSTANCE_TYPE}"
if [[ "${TEST_MODE}" -eq 1 ]]; then INSTANCE="${TEST_INSTANCE_TYPE}"; fi

OUT_PREFIX="wes_oqfe_chr${CHR}_gbat_testmode${TEST_MODE}"

EXTRA_OPTS="${EXTRA_OPTIONS:-}"
if [[ "${TEST_MODE}" -eq 1 && -z "${EXTRA_OPTS}" ]]; then
  EXTRA_OPTS=""
  # Example if you want region restriction:
  # EXTRA_OPTS="--start ${TEST_RANGE_START} --end ${TEST_RANGE_END}"
fi

echo "[INFO] instance-type: ${INSTANCE}"
echo "[INFO] output_prefix: ${OUT_PREFIX}"
echo "[INFO] destination: ${DEST_SAIGE}"
[[ -n "${EXTRA_OPTS}" ]] && echo "[INFO] extra_options: ${EXTRA_OPTS}"

JOB_ID="$(dx run "${APP_GBAT}" \
  --yes --brief \
  --instance-type "${INSTANCE}" \
  -igenotypes_bgen="${BGEN_ID}" \
  -igenotypes_bgen_bgi="${BGI_ID}" \
  -isample_txt="${SAMPLE_ID}" \
  -imodel_rda="${MODEL_RDA_ID}" \
  -ivariance_ratio_txt="${VARIANCE_RATIO_ID}" \
  -igroup_txt="${GROUP_TXT_ID}" \
  -isparse_sigma_mtx="${SPARSE_SIGMA_MTX_ID}" \
  -ioutput_file_prefix="${OUT_PREFIX}" \
  -iextra_options="${EXTRA_OPTS}" \
  --destination "${DEST_SAIGE}")"

echo "[OK] Submitted GBAT job: ${JOB_ID}"
echo "[INFO] Watch with: dx watch ${JOB_ID}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_LOCAL="${ROOT}/configs/chr22_plumbing.state.env"

if [[ ! -f "${STATE_LOCAL}" ]]; then
  cat > "${STATE_LOCAL}" <<STATE
# Auto-generated by 04_submit_step2_gbat_dx.sh on $(date -u)
DEST_PERSIST="${DEST_PERSIST}"
DEST_SAIGE="${DEST_SAIGE}"
STATE
fi

{
  echo ""
  echo "# Added by 04_submit_step2_gbat_dx.sh on $(date -u)"
  echo "GBAT_JOB_ID=\"${JOB_ID}\""
  echo "GBAT_OUT_PREFIX=\"${OUT_PREFIX}\""
} >> "${STATE_LOCAL}"

dx rm -f "${DX_PROJECT_ID}:${DEST_PERSIST}/chr22_plumbing.state.env" >/dev/null 2>&1 || true
dx upload "${STATE_LOCAL}" --path "${DEST_PERSIST}" --parents >/dev/null

echo "[OK] Updated state persisted: ${DEST_PERSIST}/chr22_plumbing.state.env"
