#!/usr/bin/env bash
set -euo pipefail

CFG="${1:-}"
[[ -n "${CFG}" && -f "${CFG}" ]] || { echo "Usage: $0 <config.env>" >&2; exit 1; }
# shellcheck disable=SC1090
source "${CFG}"

: "${DX_PROJECT_ID:?Must set DX_PROJECT_ID in config}"
: "${DEST_PERSIST:=/persist/rv_portability/saige_chr22_plumbing}"
: "${DEST_SAIGE:=/saige/chr22_test}"
: "${APP_GBAT:=saige_gwas_gbat}"
: "${CHR:=22}"

: "${TEST_MODE:=1}"
: "${TEST_INSTANCE_TYPE:=mem1_hdd1_v2_x16}"
: "${FULL_INSTANCE_TYPE:=mem1_hdd1_v2_x72}"

# Optional test-range (only used if you set EXTRA_OPTIONS below)
: "${TEST_RANGE_START:=1}"
: "${TEST_RANGE_END:=5000000}"

die() { echo "ERROR: $*" >&2; exit 1; }

echo "=============================="
echo "[INFO] Stage 04: submit Step2 GBAT"
echo "[INFO] CFG=${CFG}"
echo "[INFO] DX_PROJECT_ID=${DX_PROJECT_ID}"
echo "=============================="

dx select "${DX_PROJECT_ID}" >/dev/null

# Load manifest (for genotype IDs)
MANIFEST_DX="${DX_PROJECT_ID}:${DEST_PERSIST}/manifest_ids.env"
dx download "${MANIFEST_DX}" -o /tmp/manifest_ids.env --overwrite >/dev/null
# shellcheck disable=SC1091
source /tmp/manifest_ids.env

: "${BGEN_ID:?Missing BGEN_ID in manifest}"
: "${BGI_ID:?Missing BGI_ID in manifest}"
: "${SAMPLE_ID:?Missing SAMPLE_ID in manifest}"

# For Step2 we need outputs from Step1 + Sparse step:
# You should explicitly set these IDs in chr22_plumbing.env once Step1 finished.
# (plumbing best practice: don’t guess filenames)
: "${MODEL_RDA_ID:=}"
: "${VARIANCE_RATIO_ID:=}"
: "${SPARSE_SIGMA_MTX_ID:=}"
: "${GROUP_TXT_ID:=}"

if [[ -z "${MODEL_RDA_ID}" || -z "${VARIANCE_RATIO_ID}" || -z "${SPARSE_SIGMA_MTX_ID}" || -z "${GROUP_TXT_ID}" ]]; then
  cat >&2 <<MSG
ERROR: Missing one or more required Step2 inputs.
Please set these in configs/chr22_plumbing.env (copy/paste file IDs):
  MODEL_RDA_ID="file-..."
  VARIANCE_RATIO_ID="file-..."
  SPARSE_SIGMA_MTX_ID="file-..."
  GROUP_TXT_ID="file-..."

Tip to find them after Step1 finishes:
  dx ls ${DEST_SAIGE}
  # then:
  dx find data --path "${DX_PROJECT_ID}:${DEST_SAIGE}" --name "*.rda" --brief | head
  dx find data --path "${DX_PROJECT_ID}:${DEST_SAIGE}" --name "*varianceRatio*" --brief | head
  dx find data --path "${DX_PROJECT_ID}:${DEST_SAIGE}" --name "*sigma*" --brief | head
MSG
  exit 1
fi

INSTANCE="${FULL_INSTANCE_TYPE}"
if [[ "${TEST_MODE}" -eq 1 ]]; then INSTANCE="${TEST_INSTANCE_TYPE}"; fi

OUT_PREFIX="wes_oqfe_chr${CHR}_gbat_testmode${TEST_MODE}"

# Optional: pass a short region restriction during testing (if desired)
EXTRA_OPTS="${EXTRA_OPTIONS:-}"
if [[ "${TEST_MODE}" -eq 1 && -z "${EXTRA_OPTS}" ]]; then
  # Keep default empty unless you WANT region restriction.
  # Example: EXTRA_OPTS="--start ${TEST_RANGE_START} --end ${TEST_RANGE_END}"
  EXTRA_OPTS=""
fi

echo "[INFO] instance-type: ${INSTANCE}"
echo "[INFO] output_prefix: ${OUT_PREFIX}"
echo "[INFO] destination: ${DEST_SAIGE}"
[[ -n "${EXTRA_OPTS}" ]] && echo "[INFO] extra_options: ${EXTRA_OPTS}"

JOB_ID="$(dx run "${APP_GBAT}" \
  --yes --brief \
  --instance-type "${INSTANCE}" \
  -igenotypes_bgen="${BGEN_ID}" \
  -igenotypes_bgen_bgi="${BGI_ID}" \
  -isample_txt="${SAMPLE_ID}" \
  -imodel_rda="${MODEL_RDA_ID}" \
  -ivariance_ratio_txt="${VARIANCE_RATIO_ID}" \
  -igroup_txt="${GROUP_TXT_ID}" \
  -isparse_sigma_mtx="${SPARSE_SIGMA_MTX_ID}" \
  -ioutput_file_prefix="${OUT_PREFIX}" \
  -iextra_options="${EXTRA_OPTS}" \
  --destination "${DEST_SAIGE}")"

echo "[OK] Submitted GBAT job: ${JOB_ID}"
echo "[INFO] Watch with: dx watch ${JOB_ID}"

# Update local state then persist
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_LOCAL="${ROOT}/configs/chr22_plumbing.state.env"

if [[ ! -f "${STATE_LOCAL}" ]]; then
  cat > "${STATE_LOCAL}" <<STATE
# Auto-generated by 04_submit_step2_gbat_dx.sh on $(date -u)
DEST_PERSIST="${DEST_PERSIST}"
DEST_SAIGE="${DEST_SAIGE}"
STATE
fi

{
  echo ""
  echo "# Added by 04_submit_step2_gbat_dx.sh on $(date -u)"
  echo "GBAT_JOB_ID=\"${JOB_ID}\""
  echo "GBAT_OUT_PREFIX=\"${OUT_PREFIX}\""
} >> "${STATE_LOCAL}"

dx rm -f "${DX_PROJECT_ID}:${DEST_PERSIST}/chr22_plumbing.state.env" >/dev/null 2>&1 || true
dx upload "${STATE_LOCAL}" --path "${DEST_PERSIST}" --parents >/dev/null

echo "[OK] Updated state persisted: ${DEST_PERSIST}/chr22_plumbing.state.env"
